

site_name: Quanta.Guru


extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    
theme:
  name: 'rtd-dropdown'
  highlightjs: true
  hljs_languages: []
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: false
  sticky_navigation: true
  collapse_navigation: true
 
 
  
      
markdown_extensions:
  - codehilite:
      linenums: false
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: manni



nav:
- Home: index.md

- Getting started:
  - Guide to starting Python: GettingStarted/anaconda.md
  - Guide to Python Libraries: GettingStarted/lib.md
  - Setting up Python Environment: GettingStarted/env.md
  - Installing Jupyter Notebook : GettingStarted/jupyter.md
  - How to Git: GettingStarted/git.md

  
- Quantum Gates:
  - Getting Started: intro/qiskit.md
  - Single Qubit Gates: gates/sgates/sgates.md
  - Multiple Qubits Gates: gates/mgates/mgates.md


- Quantum Circuits:
  - Hadamard Gate: circuits/hadamard/hadamard.md
  - Bell State: circuits/bell/bell.md
  - Random Variables : circuits/random/random.md
 


- Algorithms:
  - Quantum Fourier Transform: algorithms/qft/qft.md
  - Linear Equation (HHL): algorithms/hhl/hhl.md
  - Shor's Algorithm: algorithms/shor/shor.md
  - Grover's Algorithm: algorithms/grover/grover.md


- Optimization:
  - Binary Quadratic Model (BQM): optimization/dwave/dwave.md
  - Vahicle Routing : optimization/routing/routing.md
  - Travelling Salsesman : optimization/salesman/salesman.md


- Quantum Machine Learning:
  - Quantum SVM: qml/qsvm/qsvm.md
         
  
- References:
  - Reference: References/ref.md
 
 
 
 
 
